---
title: "STA 230 Project 1"
author: "Stella Lee, Tanvi Jindal"
date: "2/15/2019"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(readr)
library(dplyr)
library(tidyr)
library(maps)     # Provides latitude and longitude data for various maps
```

## Research Question
How does a country’s happiness score get influenced by the following factors:
  1.  GDP per capita
  2. Life Expectancy
  3. Trust in the government
  4. Region

Does time have an effect on this?

Data Source: World Happiness Report 
https://www.kaggle.com/unsdsn/world-happiness

## Upload data
```{r}
happy09 <- read.csv("https://raw.githubusercontent.com/stellasylee/WorldHappinessData/master/Data/2009HPI.csv")
happy12 <- read.csv("https://raw.githubusercontent.com/stellasylee/WorldHappinessData/master/Data/2012HPI.csv")
happy16 <- read.csv("https://raw.githubusercontent.com/stellasylee/WorldHappinessData/master/Data/2016HPI.csv")
variables <- read.csv("https://raw.githubusercontent.com/stellasylee/WorldHappinessData/master/Data/OtherVariables.csv")


```

## Data Cleaning
```{r}
# Select the columns that we are going to use and change the name of columns
# Set country names as identical for every data
# 2009
happy09 <- select(happy09, country, HPI, GDP.per.capita....PPP.)
names(happy09) <- c("country", "HPI09", "GDP09")
happy09$country <- as.character(happy09$country)
happy09$country[happy09$country == "Burma"] <- "Myanmar"
happy09$country[happy09$country == "Korea"] <- "South Korea"
happy09$country[happy09$country == "Congo"] <- "Republic of Congo" 
happy09$country[happy09$country == "Congo, Dem. Rep. of the"] <- "Democratic Republic of the Congo"

# 2012
happy12 <- select(happy12, Country, Happy.Planet.Index, GDP.capita...PPP.)
names(happy12) <- c("country", "HPI12", "GDP12")
happy12$country <- as.character(happy12$country)
happy12$country[happy12$country == "Korea"] <- "South Korea"
happy12$country[happy12$country == "Congo"] <- "Republic of Congo" 
happy12$country[happy12$country == "Congo, Dem. Rep. of the"] <- "Democratic Republic of the Congo"

# 2016
happy16 <- select(happy16, Country, Region, Happy.Planet.Index, X.GDP.capita...PPP.. )
names(happy16) <- c("country","region","HPI16", "GDP16")
happy16$country <- as.character(happy16$country)

# variables
variables <- filter(variables, year == "2009" | year == "2012" | year == "2016")
var <- select (variables, country, year, Healthy.life.expectancy.at.birth, Perceptions.of.corruption)
names(var) <- c("country", "year", "lifeExpect", "corruption") 
var$year <- as.character(var$year)
var$country <- as.character(var$country)
var$country[var$country == "Congo (Brazzaville)"] <- "Republic of Congo" 
var$country[var$country == "Congo (Kinshasa)"] <- "Democratic Republic of the Congo"
var$country[var$country == "Hong Kong S.A.R. of China"] <- "Hong Kong"
var$country[var$country == "United States"] <- "United States of America"
var$country[var$country == "Palestinian Territories"] <- "Palestine"
```

## Data Merging  
```{r}
# Combine
happy <- full_join(x=happy16, y=happy12, by = "country")
happy <- full_join(x=happy, y=happy09, by = "country")
happy$country[happy09$country == "Burma"] <- "Myanmar"
happy$GDP09 <- parse_number(happy$GDP09)
happy$GDP12 <- parse_number(happy$GDP12)
happy$GDP16 <- parse_number(happy$GDP16)
#happy <- happy[complete.cases(happy), ]
```

## Tidy Data
```{r}
happy <- gather(data = happy, key = year, value = Index, 3:8)
happy <- separate(happy, year, into = c("variable", "year"), sep = -3)
happy$year<- paste0("20", happy$year)
happy <- spread (data = happy, key = variable, value = Index)
happy <- left_join(x = happy, y = var, by = c("country", "year"))
``` 

## Visualization
```{r}
# Map with region and Happiness
# Base world map
World <- map_data("world")
# Change the column and row for matching with the Happiness dataset
names(World) <- c("long", "lat", "group", "order", "country", "subregion")
World$country[World$country == "USA"] <- "United States of America" 
World$country[World$country == "UK"] <- "United Kingdom" 
World$country[World$subregion == "Hong Kong"] <- "Hong Kong" 
World$country[World$country == "Trinidad" |World$country == "Tobago" ] <- "Trinidad and Tobago" 

# Join the map, happiness data for visualization
final <- full_join(World, happy, by = "country")
final09 <- filter(happy, year == "2009")
final12 <- filter(happy, year == "2012")
final16 <- filter(happy, year == "2016")

map09 <- full_join(World, final09, by = "country")
map12 <- full_join(World, final12, by = "country")
map16 <- full_join(World, final16, by = "country")
```

# GDP and HPI
```{r}
p <- ggplot()
GDPMap09 <- p + geom_polygon(data=map09, 
          aes(x=long, y=lat, group=group, fill = GDP), 
          color="white", size = 0.2) + scale_fill_gradientn(colours = rainbow(6))
happyMap09 <- p + geom_polygon( data=map09, 
          aes(x=long, y=lat, group=group, fill = HPI), 
          color="white", size = 0.2) + scale_fill_gradientn(colours = rainbow(6))
GDPMap09
happyMap09

```
 
