---
title: "World Happiness"
author: "Stella Lee Tanvi Jindal"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction Slide

- Bulleted list
- Bullet 2
    - Sub-bullet
    
1. Numbered list
2. include a **bold** word or an *italicized* word

## Nice Visuals (notice plotly is compatible)

```{r, warning = FALSE, message = FALSE}
install.packages("kableExtra")
library(plotly)
library(kableExtra)

p <- ggplot(txhousing, aes(date, median)) +
  geom_line(aes(group = city), alpha = 0.2)

subplot(
  p, ggplotly(p, tooltip = "city"), 
  ggplot(txhousing, aes(date, median)) + geom_bin2d(),
  ggplot(txhousing, aes(date, median)) + geom_hex(),
  nrows = 2, shareX = TRUE, shareY = TRUE,
  titleY = FALSE, titleX = FALSE
)

```

## Data Display (kable produces nice html tables)

```{r}
knitr::kable(head(txhousing, 50)) %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  scroll_box(width = "100%", height = "500px")

## See: https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html for more
```

## $\LaTeX$ typesetting

- In-line equations: $\hat{y} = X\beta + \epsilon$

- Out-of-line equations:

$$\sigma^2 = \frac{1}{N}\sum_{i=1}^N (x_i - \mu)^2$$
